
name: NAF-Rain100L-width16
model_type: NAFNetModel
scale: 1
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: Rain100L
    type: PairedImageDataset
    dataroot_gt1: ../Dataset/Rain100L/Train/Gt
    dataroot_lq1: ../Dataset/Rain100L/Train/Rain

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_flip: true
    use_rot: true
    use_hflip: true      
    use_vflip: false   

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 60
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Rain100L
    type: PairedImageDataset
    dataroot_gt: ../Dataset/Rain100L/Test/Gt
    dataroot_lq: ../Dataset/Rain100L/Test/Rain
    io_backend:
      type: disk


network_g:
  type: NAF_Baseline
  width: 16
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  dw_expand: 1
  ffn_expand: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: MultiStepLR
    milestones: [20000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1000
  save_img: false
  save_vis: true  # 🆕 新增：是否保存频域分解的可视化结果
  save_vis_freq: ~  # 🆕 新增：频域分解可视化结果保存频率
  max_val_num: 40  # 🆕 新增：最大验证图像数量


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 2
  save_checkpoint_freq: !!float 100
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
# dist_params:
#   backend: nccl
#   port: 29500
